-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0

NDefines.NCharacter.PORTRAIT_ADULT_MALE_AGE_THRESHOLD = 14
NDefines.NCharacter.PORTRAIT_ADULT_FEMALE_AGE_THRESHOLD = 14
NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 40
NDefines.NCharacter.PORTRAIT_OLD_AGE_THRESHOLD = 60
NDefines.NCharacter.AGE_OF_ADULTHOOD_MALE = 18
NDefines.NCharacter.AGE_OF_ADULTHOOD_FEMALE = 18
NDefines.NCharacter.AGE_OF_MARRIAGE_MALE = 18
NDefines.NCharacter.AGE_OF_MARRIAGE_FEMALE = 18
NDefines.NCharacter.AGE_ADULT = 40
NDefines.NCharacter.AGE_OLD = 60
NDefines.NCharacter.AGE_VERY_OLD = 80
NDefines.NCharacter.MAX_CHILD_BIRTH_AGE = 50
NDefines.NCharacter.BASE_NR_OF_CHILDREN_PER_COUPLE = 0
NDefines.NCharacter.EXTRA_NR_OF_CHILDREN_FOR_PLAYERS = 0
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_0 = 0
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_10 = 0
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_20 = 0
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_30 = 0
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_40 = 25
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_50 = 50
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_60 = 200
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_70 = 1000
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_80 = 2000
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_90 = 4000
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_100 = 8000
NDefines.NCharacter.FERTILITY_BASE_MULT = 0.25
NDefines.NCharacter.INFANT_DEATH_CHANCE = 0
NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 65

NDefines.NTitle.MAX_CROWN_LAW_CHANGES = -1
NDefines.NTitle.DE_JURE_ASSIMILATION_YEARS = 25
NDefines.NTitle.ALLOW_DE_JURE_ASSIMILATION_ANYWHERE = 0
NDefines.NTitle.MAX_REPUBLIC_COUNTIES_IN_REALM = 1
NDefines.NTitle.MAX_THEOCRACY_COUNTIES_IN_REALM = 1
NDefines.NTitle.THEOCRACY_COUNTIES_CAN_BORDER = 1
NDefines.NTitle.REPUBLIC_COUNTIES_CAN_BORDER = 1
NDefines.NTitle.MILITARY_GOV_CREATE_KINGDOMS = 1

NDefines.NTitle.DEJURE_COUNTY_LIMIT_TO_CREATE = 0.5
NDefines.NTitle.EMPIRE_DEJURE_COUNTY_LIMIT_TO_CREATE = 0.5
NDefines.NTitle.EMPIRE_DEJURE_COUNTY_LIMIT_TO_USURP = 0.51

NDefines.NEconomy.HOLDING_SLOT_BUILD_COST_MOD = 3

NDefines.NMilitary.MERCENARY_HIRE_DISTANCE_THRESHOLD = 1200
NDefines.NMilitary.PERCENT_OF_GARRISON_DETACHED = 0
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR = 0
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR_50_OVER = 0
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR_100_OVER = 0
NDefines.NMilitary.RETINUE_FROM_REALMSIZE = 0
NDefines.NMilitary.RETINUE_HIRE_COST_MULTIPLIER = 1
NDefines.NMilitary.RETINUE_REINFORCE_COST = 1
NDefines.NMilitary.RETINUE_CONSTANT_COST = 0
NDefines.NMilitary.MIN_RETINUE = 0

NDefines.NMilitary.MAX_COMMANDERS_BARON = 1
NDefines.NMilitary.MAX_COMMANDERS_COUNT = 3
NDefines.NMilitary.MAX_COMMANDERS_DUKE = 6
NDefines.NMilitary.MAX_COMMANDERS_KING = 8
NDefines.NMilitary.MAX_COMMANDERS_EMPEROR = 12

-- Ship Combat Stats
NDefines.NMilitary.LIGHT_INFANTRY_MORALE = 1
NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = .2
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_ATTACK = 5
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_ATTACK = 0
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_DEFENSE = 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_DEFENSE = 100
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_DEFENSE = 1
NDefines.NMilitary.LIGHT_INFANTRY_GRAPHICAL_FACTOR = 10

NDefines.NMilitary.HEAVY_INFANTRY_MORALE = 1
NDefines.NMilitary.HEAVY_INFANTRY_MAINTENANCE = 0.4
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_ATTACK = 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_ATTACK = 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_DEFENSE = 2
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_DEFENSE = 50
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_DEFENSE = 1
NDefines.NMilitary.HEAVY_INFANTRY_GRAPHICAL_FACTOR = 10

NDefines.NMilitary.PIKEMEN_MORALE = 100
NDefines.NMilitary.PIKEMEN_MAINTENANCE = .1
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_ATTACK = 3
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_ATTACK = 0
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 1
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_DEFENSE = 2
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_DEFENSE = 50
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_DEFENSE = 1
NDefines.NMilitary.PIKEMEN_GRAPHICAL_FACTOR = 10

NDefines.NMilitary.LIGHT_CAVALRY_MORALE = 100
NDefines.NMilitary.LIGHT_CAVALRY_MAINTENANCE = 10
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_ATTACK = 25
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_ATTACK = 0
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 10
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_DEFENSE = 100
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_DEFENSE = 10
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_DEFENSE = 10
NDefines.NMilitary.LIGHT_CAVALRY_GRAPHICAL_FACTOR = 1
	
NDefines.NMilitary.KNIGHTS_MORALE = 100
NDefines.NMilitary.KNIGHTS_MAINTENANCE = 20
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_ATTACK = 10
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_ATTACK = 25
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 25
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_DEFENSE = 200
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_DEFENSE = 25
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_DEFENSE = 25
NDefines.NMilitary.KNIGHTS_GRAPHICAL_FACTOR = 1

NDefines.NMilitary.ARCHERS_MORALE = 10
NDefines.NMilitary.ARCHERS_MAINTENANCE = 2
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_ATTACK = 0
NDefines.NMilitary.ARCHERS_PHASE_MELEE_ATTACK = 0
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_ATTACK = 50
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_DEFENSE = 100
NDefines.NMilitary.ARCHERS_PHASE_MELEE_DEFENSE = 10
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_DEFENSE = 50
NDefines.NMilitary.ARCHERS_GRAPHICAL_FACTOR = 1

NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 2998
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 3000
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 4000

NDefines.NAI.MAX_EMPIRE_TITLES_TO_CREATE = 1
NDefines.NAI.AI_EMPEROR_CREATES_KINGDOMS = 1
